name: 'goshu-app'

version: '3.9'

services:
  app:
    # build: .
    image: your-dockerhub-username/goshu-app:latest
    container_name: goshu-server
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      MONGO_URI: mongodb://admin:123456@mongo:27017
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: goshu-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
